INSERT INTO PACKAGE (PACKAGEID, NAME) VALUES (1001, 'sport');
INSERT INTO PACKAGE (PACKAGEID, NAME) VALUES (1002, 'movie');

INSERT INTO CHANNEL (CHANNELID, NAME, LANGUAGE, PACKAGEID) VALUES (2001, 'ESPN', 'English', 1001);
INSERT INTO CHANNEL (CHANNELID, NAME, LANGUAGE, PACKAGEID) VALUES (2002, 'ESPN2', 'English', 1001);
INSERT INTO CHANNEL (CHANNELID, NAME, LANGUAGE, PACKAGEID) VALUES (2003, 'HBO', 'English', 1002);
INSERT INTO CHANNEL (CHANNELID, NAME, LANGUAGE, PACKAGEID) VALUES (2004, 'Cinemax', 'Spanish', 1002);


