CREATE TABLE `user` (
  `userid` int(11) PRIMARY KEY AUTO_INCREMENT,
  `username` varchar(64) UNIQUE NOT NULL,
  `password` varchar(64) DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT NULL,
  `role` varchar(64) DEFAULT NULL,
  `email` varchar(64)DEFAULT NULL
)  AUTO_INCREMENT=1000000;

CREATE TABLE PACKAGE (
  PACKAGEID  INT(11) PRIMARY KEY AUTO_INCREMENT,
  NAME  VARCHAR(255) NOT NULL,
  `type` varchar(16),
  `infopagesd` varchar(45),
  `infopagehd` varchar(45),
  `infopagepctv` varchar(45)
) AUTO_INCREMENT=10000000;

CREATE TABLE LANG (
  `langid` int(11) PRIMARY KEY AUTO_INCREMENT,
  `packageid` int(11) NOT NULL,
  `language` VARCHAR(30) NOT NULL,
  `translation` VARCHAR(255),
  CONSTRAINT FK_PACKAGE_LANG FOREIGN KEY(packageid) REFERENCES PACKAGE(PACKAGEID) ON DELETE CASCADE
) AUTO_INCREMENT=19000000;

CREATE TABLE CHANNEL (
  CHANNELID  INT(11) PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  LANGUAGE VARCHAR(255) NOT NULL DEFAULT ''
) AUTO_INCREMENT=20000000;

CREATE TABLE PACKAGE_CHANNEL (
  PACKAGEID  INT(11) NOT NULL,
  CHANNELID  INT(11) NOT NULL,
  CONSTRAINT FK_PACKAGE_CHANNEL FOREIGN KEY(PACKAGEID) REFERENCES PACKAGE(PACKAGEID) ON DELETE CASCADE,
  CONSTRAINT FK_CHANNEL_PACKAGE FOREIGN KEY(CHANNELID) REFERENCES CHANNEL(CHANNELID) ON DELETE CASCADE
);

CREATE TABLE CLIENT (
  CLIENTID       INT(11) PRIMARY KEY AUTO_INCREMENT,
  USERNAME       VARCHAR(64)  NOT NULL,
  PASSWORD       VARCHAR(64)  NOT NULL,
  FIRSTNAME      VARCHAR(80)  NOT NULL,
  LASTNAME       VARCHAR(80)  NOT NULL,
  EMAIL          VARCHAR(80)  NOT NULL,
  PHONE          VARCHAR(30)  NOT NULL,
  LANGUAGE       VARCHAR(30)  DEFAULT NULL,
  PINCODE        VARCHAR(8)   NOT NULL DEFAULT '1234',
  ADDRESS        VARCHAR(255) NOT NULL,
  CITY           VARCHAR(80)  NOT NULL,
  ZIPCODE        VARCHAR(10)  NOT NULL,
  STATE          VARCHAR(80)  NOT NULL,
  COUNTRY        VARCHAR(2)   DEFAULT NULL,
  EXPIRATIONTIME DATETIME DEFAULT NULL,
  LASTACCESS     DATETIME DEFAULT NULL,
  REGISTERED     DATETIME DEFAULT NULL
) AUTO_INCREMENT = 30000000;

CREATE TABLE CLIENT_PACKAGE (
  CLIENTID  INT(11) NOT NULL,
  PACKAGEID INT(11) NOT NULL,
  CONSTRAINT FK_CLIENT_PACKAGE FOREIGN KEY (CLIENTID) REFERENCES CLIENT (CLIENTID) ON DELETE CASCADE,
  CONSTRAINT FK_PACKAGE_CLIENT FOREIGN KEY (PACKAGEID) REFERENCES PACKAGE (PACKAGEID) ON DELETE CASCADE
);


